name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-mlops-pipeline:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-pipeline

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize ZenML
        run: |
          zenml init || true

      - name: Setup Stack
        run: |
          zenml experiment-tracker register mlflow_tracker --flavor=mlflow || true
          zenml data-validator register evidently_validator --flavor=evidently || true
          zenml stack register mlops_stack \
            -o default \
            -a default \
            -e mlflow_tracker \
            -dv evidently_validator || true
          zenml stack set mlops_stack

      - name: Run Pipeline
        run: |
          python run.py
      # -------------------------------
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .
      # -------------------------------
      - name: Run Docker Container
        run: |
          docker run --rm $IMAGE_NAME:latest
      # -------------------------------
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      # -------------------------------
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
