name: MLOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-mlops-pipeline:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-pipeline

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # -----------------------
      # Run ZenML pipeline
      # -----------------------
      - name: Run Pipeline
        run: |
          zenml init || true
          python run.py

      # -----------------------
      # Ensure model exists
      # -----------------------
      - name: Verify MLflow Output
        run: |
          ls -la mlruns || exit 1

      # -----------------------
      # Build Docker
      # -----------------------
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      # -----------------------
      # Test API container
      # -----------------------
      - name: Run API Container Test
        run: |
          docker run -d -p 8000:8000 \
            -v $(pwd)/mlruns:/app/mlruns \
            $IMAGE_NAME:latest

          sleep 10

          curl http://localhost:8000/

      # -----------------------
      # Push Docker
      # -----------------------
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
